<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { doAction } from '@/api'
import { useModalStore } from '@/stores/modal'
import PageHeader from '@/components/PageHeader.vue'
import HelpTip from '@/components/HelpTip.vue'

interface FilterRule { id: number; group: number; name: string; pri: number; include: string | string[]; exclude: string | string[]; size: string; free?: string; free_text?: string }
interface RuleGroup { id: number; name: string; default?: string; rules: FilterRule[] }
interface InitRuleGroup { id: number; name: string; rules: Array<{ name: string; include: string | string[]; exclude: string | string[] }> }

const modal = useModalStore()
const groups = ref<RuleGroup[]>([])
const initGroups = ref<InitRuleGroup[]>([])
const loading = ref(false)
const expandedGroups = ref<Set<number>>(new Set())
const FREE_OPTIONS = [{ value: '', label: '全部' }, { value: '1.0 1.0', label: '普通' }, { value: '1.0 0.0', label: '免费' }, { value: '2.0 0.0', label: '2X免费' }]
const PRI_OPTIONS = Array.from({ length: 20 }, (_, i) => i + 1)

const ruleDialog = ref(false)
const ruleSaving = ref(false)
const ruleForm = reactive({ rule_id: '' as string | number, group_id: '' as string | number, group_name: '', rule_name: '', rule_pri: 1, rule_include: '', rule_exclude: '', rule_sizelimit: '', rule_free: '' })
const groupDialog = ref(false)
const groupSaving = ref(false)
const groupForm = reactive({ name: '', default: false })
const shareVisible = ref(false)
const shareContent = ref('')
const importVisible = ref(false)
const importSaving = ref(false)
const importContent = ref('')
const restoreVisible = ref(false)
const restoreSaving = ref(false)
const restoreSelected = ref<number[]>([])

function toggleGroup(id: number) { const next = new Set(expandedGroups.value); next.has(id) ? next.delete(id) : next.add(id); expandedGroups.value = next }
function splitArr(value: string | string[] | undefined): string[] { if (!value) return []; const values = Array.isArray(value) ? value : [value]; return values.flatMap((item) => item.split('\n').map((v) => v.trim()).filter(Boolean)) }
async function load() { loading.value = true; try { const res = await doAction<{ code: number; msg?: string; ruleGroups?: RuleGroup[]; initRules?: InitRuleGroup[] }>('get_filterrules', {}); if (res.code === 0) { groups.value = res.ruleGroups || []; initGroups.value = res.initRules || []; expandedGroups.value = new Set((res.ruleGroups || []).map((group) => group.id)) } else modal.error(res.msg || '获取过滤规则失败') } catch (error) { modal.error(error instanceof Error ? error.message : '获取过滤规则失败') } finally { loading.value = false } }
function applyTemplate(rule: InitRuleGroup['rules'][number]) { ruleForm.rule_name = rule.name; ruleForm.rule_include = splitArr(rule.include).join('\n'); ruleForm.rule_exclude = splitArr(rule.exclude).join('\n') }
function openAddRule(group: RuleGroup) { Object.assign(ruleForm, { rule_id: '', group_id: group.id, group_name: group.name, rule_name: '', rule_pri: 1, rule_include: '', rule_exclude: '', rule_sizelimit: '', rule_free: '' }); ruleDialog.value = true }
async function openEditRule(group: RuleGroup, rule: FilterRule) { const res = await doAction<{ code: number; msg?: string; info?: FilterRule }>('filterrule_detail', { ruleid: rule.id, groupid: group.id }); if (res.code === 0 && res.info) { Object.assign(ruleForm, { rule_id: res.info.id, group_id: group.id, group_name: group.name, rule_name: res.info.name, rule_pri: res.info.pri || 1, rule_include: splitArr(res.info.include).join('\n'), rule_exclude: splitArr(res.info.exclude).join('\n'), rule_sizelimit: res.info.size || '', rule_free: res.info.free || '' }); ruleDialog.value = true } else modal.error(res.msg || '获取规则详情失败') }
async function submitRule() { if (!ruleForm.rule_name) return modal.warning('规则名称不能为空'); if (ruleForm.rule_sizelimit && !/^[0-9,]*$/.test(ruleForm.rule_sizelimit)) return modal.warning('大小限制只能包含数字和逗号'); ruleSaving.value = true; try { const res = await doAction<{ code: number; msg?: string }>('add_filterrule', { rule_id: ruleForm.rule_id, group_id: ruleForm.group_id, rule_name: ruleForm.rule_name, rule_pri: ruleForm.rule_pri, rule_include: ruleForm.rule_include, rule_exclude: ruleForm.rule_exclude, rule_sizelimit: ruleForm.rule_sizelimit, rule_free: ruleForm.rule_free }); if (res.code === 0) { ruleDialog.value = false; modal.success('保存成功'); load() } else modal.error(res.msg || '保存失败') } finally { ruleSaving.value = false } }
async function deleteRule(rule: Pick<FilterRule, 'id' | 'name'>) { const ok = await modal.confirm(`确认删除规则「${rule.name}」？`); if (!ok) return; const res = await doAction<{ code: number; msg?: string }>('del_filterrule', { id: rule.id }); if (res.code === 0) { ruleDialog.value = false; modal.success('删除成功'); load() } else modal.error(res.msg || '删除失败') }
function openAddGroup() { groupForm.name = ''; groupForm.default = false; groupDialog.value = true }
async function submitGroup() { if (!groupForm.name) return modal.warning('规则组名称不能为空'); groupSaving.value = true; try { const res = await doAction<{ code: number; msg?: string }>('add_filtergroup', { name: groupForm.name, default: groupForm.default ? 'Y' : 'N' }); if (res.code === 0) { groupDialog.value = false; modal.success('新增成功'); load() } else modal.error(res.msg || '新增失败') } finally { groupSaving.value = false } }
async function deleteGroup(group: RuleGroup) { const ok = await modal.confirm(`删除规则组后，该组下所有规则将同时被删除，是否确认删除「${group.name}」？`); if (!ok) return; const res = await doAction<{ code: number; msg?: string }>('del_filtergroup', { id: group.id }); if (res.code === 0) { modal.success('删除成功'); load() } else modal.error(res.msg || '删除失败') }
async function setDefault(group: { id: number }) { const res = await doAction<{ code: number; msg?: string }>('set_default_filtergroup', { id: group.id }); if (res.code === 0) { modal.success('已设为默认'); load() } else modal.error(res.msg || '设置失败') }
async function shareGroup(group: RuleGroup) { const res = await doAction<{ code: number; string?: string; msg?: string }>('share_filtergroup', { id: group.id }); if (res.code === 0) { shareContent.value = res.string || ''; shareVisible.value = true } else modal.error(res.msg || '无法生成分享') }
function openImport() { importContent.value = ''; importVisible.value = true }
async function submitImport() { if (!importContent.value) return modal.warning('请粘贴规则内容'); importSaving.value = true; try { const res = await doAction<{ code: number; msg?: string }>('import_filtergroup', { content: importContent.value }); if (res.code === 0) { importVisible.value = false; modal.success('导入成功'); load() } else modal.error(res.msg || '规则导入失败') } finally { importSaving.value = false } }
function openRestore() { restoreSelected.value = []; restoreVisible.value = true }
async function submitRestore() { if (!restoreSelected.value.length) return modal.warning('请选择要恢复的规则组'); restoreSaving.value = true; try { const res = await doAction<{ code: number; msg?: string }>('restore_filtergroup', { groupids: restoreSelected.value, init_rulegroups: initGroups.value }); if (res.code === 0) { restoreVisible.value = false; modal.success('恢复成功'); load() } else modal.error('恢复失败') } finally { restoreSaving.value = false } }
onMounted(load)
</script>

<template>
  <div class="filterrule-view"><PageHeader title="过滤规则" description="管理订阅与搜索的过滤规则组"><template #actions><q-btn outline icon="restore" label="恢复" @click="openRestore" /><q-btn outline color="positive" icon="upload" label="导入" @click="openImport" /><q-btn color="primary" unelevated icon="add" label="新增" @click="openAddGroup" /></template></PageHeader><q-inner-loading :showing="loading"><q-spinner-dots color="primary" size="40px" /></q-inner-loading>
    <div v-if="!loading && !groups.length" class="empty-tip"><q-icon name="rule" size="46px" color="grey-5" /><span>没有配置任何规则，请点击“新增”按钮</span></div>
    <div v-if="initGroups.length" class="section-header"><span class="section-title">内置规则</span><q-badge outline color="grey-7" label="不可编辑" /></div>
    <div class="group-list"><q-card v-for="group in initGroups" :key="group.id" flat bordered class="group-card"><q-card-section class="group-header"><div class="group-title" role="button" tabindex="0" @click="toggleGroup(group.id)" @keydown.enter.prevent="toggleGroup(group.id)"><q-icon :name="expandedGroups.has(group.id) ? 'expand_more' : 'chevron_right'" color="grey-7" /><strong>{{ group.name }}</strong><q-badge color="grey-7" label="内置" /></div><q-btn flat dense color="primary" icon="star" label="设默认" @click="setDefault(group)" /></q-card-section><q-slide-transition><q-card-section v-show="expandedGroups.has(group.id)" class="rule-section"><div v-if="group.rules.length" class="rule-list"><div v-for="(rule, index) in group.rules" :key="index" class="rule-item readonly"><div class="rule-name">{{ rule.name }}</div><div class="rule-tags"><q-badge v-for="(value, key) in splitArr(rule.include)" :key="`i${key}`" color="positive" :label="`包含 ${value}`" /><q-badge v-for="(value, key) in splitArr(rule.exclude)" :key="`e${key}`" color="negative" :label="`排除 ${value}`" /></div></div></div><div v-else class="inner-empty">无规则</div></q-card-section></q-slide-transition></q-card></div>
    <div v-if="groups.length" class="section-header"><span class="section-title">自定义规则</span></div><div class="group-list"><q-card v-for="group in groups" :key="group.id" flat bordered class="group-card"><q-card-section class="group-header"><div class="group-title" role="button" tabindex="0" @click="toggleGroup(group.id)" @keydown.enter.prevent="toggleGroup(group.id)"><q-icon :name="expandedGroups.has(group.id) ? 'expand_more' : 'chevron_right'" color="grey-7" /><q-icon v-if="group.default === 'Y'" name="star" color="warning" /><strong>{{ group.name }}</strong><q-badge v-if="group.default === 'Y'" color="positive" label="默认" /></div><div class="group-actions"><q-btn flat dense color="primary" icon="share" label="分享" @click="shareGroup(group)" /><q-btn flat dense color="primary" icon="star" label="设默认" @click="setDefault(group)" /><q-btn flat dense color="primary" icon="add" label="增加规则" @click="openAddRule(group)" /><q-btn flat dense color="negative" icon="delete" label="删除组" @click="deleteGroup(group)" /></div></q-card-section><q-slide-transition><q-card-section v-show="expandedGroups.has(group.id)" class="rule-section"><div v-if="group.rules.length" class="rule-list"><div v-for="rule in group.rules" :key="rule.id" class="rule-item" role="button" tabindex="0" @click="openEditRule(group, rule)" @keydown.enter.prevent="openEditRule(group, rule)"><div class="rule-name">{{ rule.name }}</div><div class="rule-tags"><q-badge v-if="rule.pri !== 1" color="primary" :label="`优先级 ${rule.pri}`" /><q-badge v-if="rule.free_text" color="info" :label="`促销 ${rule.free_text}`" /><q-badge v-for="(value, key) in splitArr(rule.include)" :key="`i${key}`" color="positive" :label="`包含 ${value}`" /><q-badge v-for="(value, key) in splitArr(rule.exclude)" :key="`e${key}`" color="negative" :label="`排除 ${value}`" /><q-badge v-if="rule.size" color="warning" :label="`大小 ${rule.size} GB`" /></div></div></div><div v-else class="inner-empty">没有规则，请点击“增加规则”</div></q-card-section></q-slide-transition></q-card></div>

    <q-dialog v-model="ruleDialog" :maximized="$q.screen.lt.sm" :full-width="!$q.screen.lt.sm" persistent><q-card class="rule-dialog"><q-card-section class="row items-center no-wrap"><div class="text-h6">{{ ruleForm.rule_id ? `编辑规则：${ruleForm.group_name}` : `新增规则：${ruleForm.group_name}` }}</div><q-space /><q-btn flat round dense icon="close" aria-label="关闭" @click="ruleDialog = false" /></q-card-section><q-separator /><q-form @submit.prevent="submitRule"><q-card-section class="dialog-body"><div class="form-grid"><q-input v-model="ruleForm.rule_name" outlined dense label="规则名称 *" placeholder="自定义规则名称" /><q-select v-model="ruleForm.rule_pri" outlined dense emit-value map-options label="优先级" :options="PRI_OPTIONS.map((value) => ({ value, label: String(value) }))"><template #append><HelpTip text="同一个规则组内，数值越小优先级越高。" /></template></q-select></div><div class="form-grid q-mt-md"><q-input v-model="ruleForm.rule_include" outlined type="textarea" autogrow label="包含规则" placeholder="必须包含的关键字或正则表达式"><template #append><HelpTip text="多行之间为与关系，单行内使用 | 表示或。" /></template></q-input><q-input v-model="ruleForm.rule_exclude" outlined type="textarea" autogrow label="排除规则" placeholder="不能包含的关键字或正则表达式"><template #append><HelpTip text="命中排除条件的种子会被跳过。" /></template></q-input></div><div class="form-grid q-mt-md"><q-input v-model="ruleForm.rule_sizelimit" outlined dense label="大小限制（GB）" placeholder="如 1,10" /><q-select v-model="ruleForm.rule_free" outlined dense emit-value map-options label="促销" :options="FREE_OPTIONS" /></div><div v-if="initGroups.length" class="template-section"><div class="template-title">规则模板</div><details v-for="group in initGroups" :key="group.id"><summary class="template-summary">模板 · {{ group.name }}</summary><div class="template-rules"><q-btn v-for="(rule, index) in group.rules" :key="index" outline dense color="primary" :label="rule.name" @click="applyTemplate(rule)" /></div></details></div></q-card-section><q-separator /><q-card-actions align="right" class="dialog-actions"><q-btn v-if="ruleForm.rule_id" flat color="negative" icon="delete" label="删除" @click="deleteRule({ id: Number(ruleForm.rule_id), name: ruleForm.rule_name })" /><q-space /><q-btn flat label="取消" @click="ruleDialog = false" /><q-btn color="primary" unelevated :loading="ruleSaving" :label="ruleForm.rule_id ? '修改' : '新增'" type="submit" /></q-card-actions></q-form></q-card></q-dialog>
    <q-dialog v-model="groupDialog" :maximized="$q.screen.lt.sm" :full-width="!$q.screen.lt.sm" persistent><q-card class="small-dialog"><q-card-section class="row items-center"><div class="text-h6">新增规则组</div><q-space /><q-btn flat round dense icon="close" aria-label="关闭" @click="groupDialog = false" /></q-card-section><q-separator /><q-form @submit.prevent="submitGroup"><q-card-section class="dialog-body"><q-input v-model="groupForm.name" outlined dense label="规则组名称 *" placeholder="别名" /><q-toggle v-model="groupForm.default" color="primary" label="设为默认规则组" /></q-card-section><q-separator /><q-card-actions align="right" class="dialog-actions"><q-btn flat label="取消" @click="groupDialog = false" /><q-btn color="primary" unelevated label="新增" :loading="groupSaving" type="submit" /></q-card-actions></q-form></q-card></q-dialog>
    <q-dialog v-model="shareVisible" :maximized="$q.screen.lt.sm" :full-width="!$q.screen.lt.sm"><q-card class="small-dialog share-dialog"><q-card-section class="row items-center"><div class="text-h6">规则分享</div><q-space /><q-btn flat round dense icon="close" aria-label="关闭" v-close-popup /></q-card-section><q-separator /><q-card-section><pre class="share-content">{{ shareContent }}</pre></q-card-section><q-card-actions align="right"><q-btn color="primary" label="关闭" v-close-popup /></q-card-actions></q-card></q-dialog>
    <q-dialog v-model="importVisible" :maximized="$q.screen.lt.sm" :full-width="!$q.screen.lt.sm" persistent><q-card class="small-dialog share-dialog"><q-card-section class="row items-center"><div class="text-h6">规则导入</div><q-space /><q-btn flat round dense icon="close" aria-label="关闭" @click="importVisible = false" /></q-card-section><q-separator /><q-card-section><q-input v-model="importContent" outlined type="textarea" autogrow label="分享内容" placeholder="粘贴分享的规则内容" /></q-card-section><q-separator /><q-card-actions align="right" class="dialog-actions"><q-btn flat label="取消" @click="importVisible = false" /><q-btn color="primary" unelevated label="导入" :loading="importSaving" @click="submitImport" /></q-card-actions></q-card></q-dialog>
    <q-dialog v-model="restoreVisible" :maximized="$q.screen.lt.sm" :full-width="!$q.screen.lt.sm" persistent><q-card class="small-dialog"><q-card-section class="row items-center"><div class="text-h6">恢复初始规则</div><q-space /><q-btn flat round dense icon="close" aria-label="关闭" @click="restoreVisible = false" /></q-card-section><q-separator /><q-card-section class="restore-group"><q-checkbox v-for="group in initGroups" :key="group.id" v-model="restoreSelected" :val="group.id" :label="group.name" color="primary" /></q-card-section><q-separator /><q-card-actions align="right" class="dialog-actions"><q-btn flat label="取消" @click="restoreVisible = false" /><q-btn color="primary" unelevated label="恢复" :loading="restoreSaving" @click="submitRestore" /></q-card-actions></q-card></q-dialog>
  </div>
</template>

<style scoped>
.filterrule-view { position: relative; }.empty-tip, .inner-empty { display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 10px; padding: 48px 0; color: var(--text-secondary); }.section-header { display: flex; align-items: center; gap: 8px; margin: 20px 0 8px; }.section-title { font-size: 15px; font-weight: 700; }.group-list { display: flex; flex-direction: column; gap: 12px; margin-bottom: 14px; }.group-card { border-radius: 14px; background: var(--surface); color: var(--text-primary); }.group-header { display: flex; align-items: center; justify-content: space-between; gap: 10px; min-height: 54px; padding: 10px 16px; }.group-title { display: flex; align-items: center; gap: 7px; min-width: 0; cursor: pointer; user-select: none; }.group-title strong { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }.group-actions { display: flex; flex-wrap: wrap; justify-content: flex-end; gap: 2px; }.rule-section { padding-top: 0; }.rule-list { display: flex; flex-direction: column; gap: 8px; }.rule-item { padding: 10px 12px; border: 1px solid var(--border-subtle); border-radius: 10px; cursor: pointer; transition: border-color .15s; }.rule-item:hover, .rule-item:focus-visible { border-color: var(--q-primary); outline: none; }.rule-item.readonly { cursor: default; }.rule-item.readonly:hover { border-color: var(--border-subtle); }.rule-name { margin-bottom: 7px; font-weight: 600; }.rule-tags { display: flex; flex-wrap: wrap; gap: 5px; }.rule-dialog, .small-dialog { width: min(720px, calc(100vw - 32px)); max-width: none; border-radius: 16px; background: var(--surface); color: var(--text-primary); }.small-dialog { width: min(480px, calc(100vw - 32px)); }.share-dialog { width: min(700px, calc(100vw - 32px)); }.dialog-body { max-height: 68vh; overflow-y: auto; padding: 20px 24px; }.form-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 14px; }.template-section { margin-top: 20px; padding-top: 14px; border-top: 1px solid var(--border-subtle); }.template-title { margin-bottom: 8px; color: var(--text-secondary); font-size: 13px; font-weight: 600; }.template-summary { padding: 5px 0; color: var(--q-primary); cursor: pointer; font-size: 13px; }.template-rules { display: flex; flex-wrap: wrap; gap: 6px; padding: 6px 0 4px 14px; }.share-content { max-height: 400px; margin: 0; overflow: auto; padding: 12px; border-radius: 8px; background: var(--surface-muted); color: var(--text-primary); white-space: pre-wrap; word-break: break-all; font: 12px/1.6 Consolas, Monaco, monospace; }.restore-group { display: flex; flex-direction: column; gap: 7px; }.dialog-actions { gap: 8px; padding: 12px 24px 16px; }
@media (max-width: 700px) { .group-header { align-items: flex-start; flex-direction: column; }.group-actions { justify-content: flex-start; width: 100%; }.form-grid { grid-template-columns: 1fr; } }
@media (max-width: 599px) { .rule-dialog, .small-dialog { width: 100%; min-height: 100dvh; border-radius: 0; }.dialog-body { max-height: none; padding: 16px; }.dialog-actions { position: sticky; bottom: 0; padding: 10px 16px calc(10px + var(--safe-bottom)); }.dialog-actions :deep(.q-btn) { min-height: 44px; } }
</style>
