<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import PageHeader from '@/components/PageHeader.vue'
import { useModalStore } from '@/stores/modal'
import { getUnknownList, delUnknownPath, reIdentification, renameUdf, type UnknownItem, type TransferMode, type ManualMediaType } from '@/api/rename'

const modal = useModalStore(); const loading = ref(false); const list = ref<UnknownItem[]>([]); const selection = ref<UnknownItem[]>([])
const transferModes: { label: string; value: TransferMode }[] = [{ label: '复制', value: 'copy' }, { label: '硬链接', value: 'link' }, { label: '软链接', value: 'softlink' }, { label: '移动', value: 'move' }, { label: 'Rclone', value: 'rclone' }, { label: 'Rclone复制', value: 'rclonecopy' }, { label: 'rustfs', value: 'rustfs' }, { label: 'rustfs复制', value: 'rustfscopy' }]
const mediaTypes: { label: string; value: ManualMediaType }[] = [{ label: '电影', value: 'movie' }, { label: '电视剧', value: 'tv' }, { label: '动漫', value: 'anime' }]
const modeLabel = (value: string) => transferModes.find((mode) => mode.value === value)?.label || value || ''; const count = computed(() => list.value.length)
async function load() { loading.value = true; try { const res = await getUnknownList(); if (res.code === 0) list.value = res.items || []; else modal.error('获取未识别列表失败') } catch (error) { modal.error(error instanceof Error ? error.message : '获取未识别列表失败') } finally { loading.value = false } }
async function onDelete(row: UnknownItem) { if (!await modal.confirm(`确认删除未识别记录「${row.name}」？`, '删除记录')) return; const res = await delUnknownPath(row.id); if (res.retcode === 0) { modal.success('删除成功'); load() } else modal.error('删除失败') }
async function onBatchDelete() { if (!selection.value.length) return modal.warning('请先选择要删除的记录'); if (!await modal.confirm(`确认删除选中的 ${selection.value.length} 条未识别记录？`, '批量删除')) return; const res = await delUnknownPath(selection.value.map((row) => row.id)); if (res.retcode === 0) { selection.value = []; modal.success('删除成功'); load() } else modal.error('删除失败') }
async function onReIdentify(row: UnknownItem) { modal.showLoading('重新识别中...'); try { const res = await reIdentification('unidentification', [row.id]); if (res.retcode === 0) { modal.success('重新识别完成'); load() } else modal.error(`识别失败：${res.retmsg || '未知错误'}`) } catch (error) { modal.error(error instanceof Error ? error.message : '识别失败') } finally { modal.hideLoading() } }
async function onBatchReIdentify() { if (!selection.value.length) return modal.warning('请先选择要重新识别的记录'); modal.showLoading('批量重新识别中...'); try { const res = await reIdentification('unidentification', selection.value.map((row) => row.id)); if (res.retcode === 0) modal.success('批量重新识别完成'); else modal.error(`处理完成：${res.retmsg || '部分识别失败'}`); load() } catch (error) { modal.error(error instanceof Error ? error.message : '识别失败') } finally { modal.hideLoading() } }
const dialogVisible = ref(false); const dialogTitle = ref('手动识别'); const submitting = ref(false); const form = reactive({ id: '' as string | number, inpath: '', outpath: '', syncmod: 'copy' as TransferMode, type: 'movie' as ManualMediaType, tmdb: '', season: '', episode_format: '', episode_details: '', episode_offset: '', min_filesize: '' })
function openManual(row?: UnknownItem) { dialogTitle.value = row ? '手动识别' : '自定义识别'; Object.assign(form, { id: row?.id ?? '', inpath: row?.path ?? '', outpath: row?.to ?? '', syncmod: (row?.sync_mode as TransferMode) || 'copy', type: 'movie', tmdb: '', season: '', episode_format: '', episode_details: '', episode_offset: '', min_filesize: '' }); dialogVisible.value = true }
async function submitManual() { if (!form.inpath) return modal.error('请输入输入路径'); if (!form.syncmod) return modal.error('请选择转移方式'); submitting.value = true; try { const res = await renameUdf({ inpath: form.inpath, outpath: form.outpath || undefined, syncmod: form.syncmod, type: form.type, tmdb: form.tmdb || undefined, season: form.season || undefined, episode_format: form.episode_format || undefined, episode_details: form.episode_details || undefined, episode_offset: form.episode_offset || undefined, min_filesize: form.min_filesize || undefined }); if (res.retcode === 0) { dialogVisible.value = false; modal.success('转移成功'); load() } else modal.error(`转移失败：${res.retmsg || '未知错误'}`) } finally { submitting.value = false } }
onMounted(load)
</script>

<template>
  <div class="unidentification"><PageHeader title="手动识别" description="处理无法自动识别的媒体文件"><template #actions><q-btn color="primary" unelevated icon="auto_fix_high" label="自定义识别" @click="openManual()" /><q-btn outline icon="refresh" label="刷新" :loading="loading" @click="load" /></template></PageHeader><q-card flat bordered class="unknown-card"><q-inner-loading :showing="loading"><q-spinner-dots color="primary" size="40px" /></q-inner-loading><q-card-section class="row items-center"><span class="text-secondary">共 {{ count }} 条记录</span><q-space /><div class="row q-gutter-xs"><q-btn flat dense color="primary" icon="published_with_changes" label="批量重新识别" :disable="!selection.length" @click="onBatchReIdentify" /><q-btn flat dense color="negative" icon="delete" label="删除选中" :disable="!selection.length" @click="onBatchDelete" /></div></q-card-section><q-separator />
    <q-table v-if="!$q.screen.lt.sm" v-model:selected="selection" flat selection="multiple" :rows="list" :columns="[{ name: 'path', label: '文件名', field: 'path', align: 'left' }, { name: 'mode', label: '转移方式', field: 'sync_mode', align: 'left' }, { name: 'actions', label: '操作', field: 'actions', align: 'right' }]" row-key="id" :loading="loading" hide-pagination :rows-per-page-options="[0]" no-data-label="没有数据"><template #body-cell-path="slotProps"><q-td :props="slotProps"><div class="file-name" :title="slotProps.row.path">{{ slotProps.row.path }}</div><div v-if="slotProps.row.to" class="file-to" :title="slotProps.row.to">⇒ {{ slotProps.row.to }}</div></q-td></template><template #body-cell-mode="slotProps"><q-td :props="slotProps"><q-badge outline color="primary" :label="modeLabel(slotProps.row.sync_mode)" /></q-td></template><template #body-cell-actions="slotProps"><q-td :props="slotProps"><div class="row justify-end q-gutter-xs"><q-btn flat round dense color="primary" icon="published_with_changes" aria-label="重新识别" @click="onReIdentify(slotProps.row)"><q-tooltip>重新识别</q-tooltip></q-btn><q-btn flat round dense color="primary" icon="edit" aria-label="手动识别" @click="openManual(slotProps.row)"><q-tooltip>手动识别</q-tooltip></q-btn><q-btn flat round dense color="negative" icon="delete" aria-label="删除" @click="onDelete(slotProps.row)"><q-tooltip>删除</q-tooltip></q-btn></div></q-td></template></q-table>
    <div v-else class="unknown-mobile-list"><q-card v-for="row in list" :key="row.id" flat bordered class="unknown-item"><q-card-section><div class="file-name" :title="row.path">{{ row.path }}</div><div v-if="row.to" class="file-to" :title="row.to">⇒ {{ row.to }}</div><q-badge outline color="primary" :label="modeLabel(row.sync_mode)" class="q-mt-sm" /></q-card-section><q-card-actions align="right"><q-btn flat color="primary" icon="published_with_changes" label="重新识别" @click="onReIdentify(row)" /><q-btn flat color="primary" icon="edit" label="手动识别" @click="openManual(row)" /><q-btn flat color="negative" icon="delete" label="删除" @click="onDelete(row)" /></q-card-actions></q-card><div v-if="!loading && !list.length" class="empty-state"><q-icon name="check_circle" size="44px" color="grey-5" />没有数据</div></div>
  </q-card>
  <q-dialog v-model="dialogVisible" :maximized="$q.screen.lt.sm" :full-width="!$q.screen.lt.sm" persistent><q-card class="manual-dialog"><q-card-section class="row items-center no-wrap"><div class="text-h6">{{ dialogTitle }}</div><q-space /><q-btn flat round dense icon="close" aria-label="关闭" @click="dialogVisible = false" /></q-card-section><q-separator /><q-form @submit.prevent="submitManual"><q-card-section class="dialog-body"><div class="form-grid"><q-input v-model="form.inpath" outlined dense label="输入路径 *" placeholder="输入文件 / 目录路径" /><q-input v-model="form.outpath" outlined dense label="输出路径" placeholder="留空按配置自动选择" /><q-select v-model="form.syncmod" outlined dense emit-value map-options label="转移方式 *" :options="transferModes" /><q-option-group v-model="form.type" type="radio" inline color="primary" label="类型" :options="mediaTypes" /></div><q-input v-model="form.tmdb" outlined dense label="TMDB ID" placeholder="留空自动识别" class="q-mt-md" /><q-banner v-if="form.type !== 'movie'" dense rounded class="bg-blue-1 text-primary q-mt-md">集数定位格式必须包含 {ep}，例如 S{season}E{ep} 或 第{ep}集；集数详情填写 1 或 1,2；偏移支持 -10、EP+1、2*EP-1。留空时按自动识别处理。</q-banner><div v-if="form.type !== 'movie'" class="form-grid q-mt-md"><q-input v-model="form.season" outlined dense label="季" placeholder="如 1" /><q-input v-model="form.episode_format" outlined dense label="集数定位格式" placeholder="如 S{season}E{ep}" /><q-input v-model="form.episode_details" outlined dense label="起始/终止集" placeholder="如 1 或 1,2" /><q-input v-model="form.episode_offset" outlined dense label="集数偏移" placeholder="如 -10 或 EP+1" /></div><q-input v-model="form.min_filesize" outlined dense label="最小文件大小" placeholder="单位 MB，留空不限" class="q-mt-md" /></q-card-section><q-separator /><q-card-actions align="right" class="dialog-actions"><q-btn flat label="取消" :disable="submitting" @click="dialogVisible = false" /><q-btn color="primary" unelevated label="开始转移" :loading="submitting" type="submit" /></q-card-actions></q-form></q-card></q-dialog>
  </div>
</template>

<style scoped>
.unidentification { position: relative; max-width: 1600px; min-width: 0; margin: 0 auto; }.unknown-card { overflow: hidden; border-radius: 16px; background: var(--surface); color: var(--text-primary); }.file-name { max-width: min(58vw, 880px); overflow: hidden; font-size: 13px; text-overflow: ellipsis; white-space: nowrap; }.file-to { max-width: min(58vw, 880px); margin-top: 3px; overflow: hidden; color: var(--text-secondary); font-size: 12px; text-overflow: ellipsis; white-space: nowrap; }.unknown-mobile-list { display: flex; flex-direction: column; gap: 10px; padding: 12px; }.unknown-item { border-radius: 12px; background: var(--surface-raised); }.empty-state { display: flex; flex-direction: column; align-items: center; gap: 8px; padding: 52px 0; color: var(--text-secondary); }.manual-dialog { width: min(640px, calc(100vw - 32px)); max-width: none; border-radius: 16px; background: var(--surface); color: var(--text-primary); }.dialog-body { padding: 20px 24px; }.form-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 14px; }.dialog-actions { gap: 8px; padding: 12px 24px 16px; }@media (max-width: 599px) { .file-name, .file-to { max-width: 100%; white-space: normal; overflow-wrap: anywhere; }.manual-dialog { width: 100%; min-height: 100dvh; border-radius: 0; }.dialog-body { padding: 16px; }.form-grid { grid-template-columns: 1fr; }.dialog-actions { position: sticky; bottom: 0; padding: 10px 16px calc(10px + var(--safe-bottom)); }.dialog-actions :deep(.q-btn) { min-height: 44px; } }
</style>
